server.port=8080
spring.application.name=api-gestion-shuttle

spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1522/XE
spring.datasource.username=USER_SHUTTLE
spring.datasource.password=shuttle123